# Site settings
email: manuel.vargas.alegria@gmail.com
# Dont change
baseurl: "/Vigia"
# Dont change
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-127545573-1

# SEO settings
title: Vigía!, open data visualization for the citizen government
description: Another blog for promote open data visualization for the citizen government. Otro blog para promover la visualización de datos abiertos para un gobierno ciudadano. 
#Dont change
url: "https://manuelvarzen.github.io/"
author: Manuel Vargas Alegría
#Dont change
twitter:
  username: manuelvarzen
  site: https://www.twitter.com/manuelvarzen
default_img: /Vigia/img/OpenData_500x300.png/
lang: es

# Profile settings
name: Vigia
profile_img: /Vigia/img/Vigia.jpg
profile: Manuel Vargas Alegría is an apprentice of the use of open data for open goverment. As such, he works on constructing questions that orient a sense to the tasks of public management as well as private activity. Feel free to contact him if you need help to ask critical questions about the meaning of the existence of technology in your organization, public or private.
social:   
    github: "https://github.com/manuelvarzen"
    twitter: "https://twitter.com/manuelvarzen"
    facebook: "https://www.facebook.com/manuelvarzen"
    linkedin: "https://www.linkedin.com/in/manuelvarzen"

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
style: compressed
