# Site settings
email: 
# Dont change
baseurl: "/Vigia"
# Dont change
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
#Dont change
url: "https://manuelvarzen.github.io/Vigia"
#Dont change
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
